using System.Text;

namespace ShojiWM.Tools;

// Reviewed local ABI definitions. Generation-time metadata never becomes a
// runtime operation tag: every emitted export makes one direct typed host call.
internal static class NativeOperationGenerator
{
    private sealed record Field(string Type, string Name, string Conversion);
    private sealed record Input(string Name, string Native, Field[] Fields);
    private sealed record Result(string Name, string Native, string Managed, Field[] Fields);
    private sealed record Operation(string Name, Input? Input, Result? Result);

    private static Input EvaluationInput(string name) => new(name, $"Swm{name}Input", [
        new("AbiWaylandWindowSnapshot*", "Snapshot", "RequiredSnapshot(input.Snapshot)"),
        new("ArenaString*", "WindowId", "OptionalString(input.WindowId)"),
        new("SwmEvaluationContext", "Context", "ReadContext(input.Context)"),
    ]);
    private static Input StringInput(string name) => new(name, "ArenaString", [new("ArenaString", "", "ReadString(input)")]);

    private static readonly Result Evaluation = new("Evaluate", "EvaluateResult", "EvaluationResult", [
        new("AbiWireDecorationNode*", "Node", "w.Put(WriteWireDecorationNode(v.Node, w, 0))"),
        new("RuntimeWindowActionSlice", "Actions", "WriteRuntimeWindowActionSlice(v.Actions, w, 0)"),
    ]);
    private static readonly Result Handler = new("InvokeHandler", "InvokeHandlerResult", "HandlerInvocationResult", [
        new("AbiWireDecorationNode*", "Node", "v.Node is {} node ? w.Put(WriteWireDecorationNode(node, w, 0)) : null"),
        new("RuntimeWindowActionSlice", "Actions", "WriteRuntimeWindowActionSlice(v.Actions, w, 0)"),
        new("byte", "Invoked", "(byte)(v.Invoked ? 1 : 0)"),
    ]);
    private static readonly Result Enable = new("LifecycleEnable", "EnableResult", "LifecycleEnableResult", [
        new("RuntimeWindowActionSlice", "Actions", "WriteRuntimeWindowActionSlice(v.Actions, w, 0)"),
        new("AbiRuntimeDebugConfigUpdate*", "DebugConfig", "v.DebugConfig is {} debug ? w.Put(WriteRuntimeDebugConfigUpdate(debug, w, 0)) : null"),
    ]);
    private static readonly Result Commit = new("CommitAssembly", "CommitResult", "AssemblyCommitResult", [
        new("AbiRuntimeDebugConfigUpdate*", "DebugConfig", "v.DebugConfig is {} debug ? w.Put(WriteRuntimeDebugConfigUpdate(debug, w, 0)) : null"),
    ]);
    private static readonly Operation[] Operations = [
        new("Evaluate", EvaluationInput("Evaluate"), Evaluation),
        new("EvaluatePreview", EvaluationInput("EvaluatePreview"), Evaluation),
        new("EvaluateCandidatePreview", EvaluationInput("EvaluateCandidatePreview"), Evaluation),
        new("EvaluateCached", new("EvaluateCached", "SwmEvaluateCachedInput", [
            new("AbiWaylandWindowSnapshot*", "Snapshot", "input.Snapshot == null ? null : ReadWaylandWindowSnapshot(*input.Snapshot, 0)"),
            new("ArenaString", "WindowId", "ReadString(input.WindowId)"),
            new("SwmEvaluationContext", "Context", "ReadContext(input.Context)"),
        ]), Evaluation),
        new("InvokeHandler", new("InvokeHandler", "SwmInvokeHandlerInput", [
            new("ArenaString", "WindowId", "ReadString(input.WindowId)"),
            new("ArenaString", "HandlerId", "ReadString(input.HandlerId)"),
            new("SwmEvaluationContext", "Context", "ReadContext(input.Context)"),
        ]), Handler),
        new("WindowClosed", StringInput("WindowClosed"), null),
        new("PrepareAssembly", StringInput("PrepareAssembly"), null),
        new("LifecycleEnable", StringInput("LifecycleEnable"), Enable),
        new("LifecycleDisable", StringInput("LifecycleDisable"), null),
        new("CommitAssembly", null, Commit),
        new("AbortAssembly", null, null),
        new("DrainPreload", null, null),
        new("ShutdownAssemblies", null, null),
    ];

    internal const string AbiOutput = "dotnet/ShojiWM.Runtime/Ffi/Generated/OperationAbi.g.cs";
    internal const string EntryOutput = "dotnet/ShojiWM.Runtime/Ffi/Generated/NativeEntryPoint.g.cs";
    private const string Header = "// <auto-generated />\n// Source: tools/NativeOperationGenerator.cs\n#nullable enable\nusing System.Runtime.InteropServices;\nnamespace ShojiWM.Runtime;\n\n";

    internal static void Run(string root, bool check)
    {
        var abi = new StringBuilder(Header);
        void Struct(string name, IEnumerable<(string Type, string Name)> fields)
        {
            abi.AppendLine($"[StructLayout(LayoutKind.Sequential)]\npublic unsafe struct {name}\n{{");
            foreach (var field in fields) abi.AppendLine($"    public {field.Type} {field.Name};");
            abi.AppendLine("}\n");
        }
        Struct("SwmEvaluationContext", [("ulong", "NowMs"), ("WaylandOutputEntrySlice", "Displays"), ("RuntimeInputEntrySlice", "Inputs")]);
        var inputs = Operations.Where(x => x.Input is not null).Select(x => x.Input!).ToArray();
        var results = Operations.Where(x => x.Result is not null).Select(x => x.Result!).Distinct().ToArray();
        foreach (var input in inputs.Where(x => x.Native != "ArenaString"))
            Struct(input.Native, input.Fields.Select(x => (x.Type, x.Name)));
        foreach (var result in results)
        {
            Struct(result.Native, result.Fields.Select(x => (x.Type, x.Name)));
            Struct($"Swm{result.Name}Result", [("int", "Status"), ("ResultArena", "Arena"), ($"{result.Native}*", "Value"), ("ArenaString*", "Error")]);
        }
        Struct("SwmStatusResult", [("int", "Status"), ("ResultArena", "Arena"), ("ArenaString*", "Error")]);
        abi.AppendLine("public static unsafe partial class AbiConvert\n{");
        foreach (var input in inputs)
            abi.AppendLine($"    internal static {input.Name}Request Read{input.Name}({input.Native} input) =>\n        new({string.Join(", ", input.Fields.Select(x => x.Conversion))});\n");
        foreach (var result in results)
        {
            abi.AppendLine($"    private static {result.Native} Build{result.Name}({result.Managed} v, ArenaWriter w) => new()\n    {{");
            foreach (var field in result.Fields) abi.AppendLine($"        {field.Name} = {field.Conversion},");
            abi.AppendLine("    };");
            abi.AppendLine($"    internal static Swm{result.Name}Result Write{result.Name}({result.Managed} value)\n    {{\n        var graph = WriteGraph(value, Build{result.Name});\n        return new() {{ Arena = graph.Arena, Value = graph.Root }};\n    }}");
            abi.AppendLine($"    private static Swm{result.Name}Result Failure{result.Name}(SwmStatusResult failure) =>\n        new() {{ Status = failure.Status, Arena = failure.Arena, Error = failure.Error }};");
            abi.AppendLine($"    internal static Swm{result.Name}Result Failure{result.Name}(NativeFailureStatus status, string message) =>\n        Failure{result.Name}(FailureStatus(status, message));");
            abi.AppendLine($"    internal static Swm{result.Name}Result Failure{result.Name}(Exception error, NativeFailureStatus status) =>\n        Failure{result.Name}(FailureStatus(error, status));\n");
        }
        abi.AppendLine("}");

        var entry = new StringBuilder(Header);
        entry.AppendLine("public static unsafe partial class NativeEntryPoint\n{");
        foreach (var operation in Operations)
        {
            string result = operation.Result is {} payload ? $"Swm{payload.Name}Result" : "SwmStatusResult";
            string failure = operation.Result?.Name ?? "Status";
            string argument = operation.Input is {} input ? $"{input.Native} input" : "";
            entry.AppendLine($"    [UnmanagedCallersOnly]\n    public static {result} SWM{operation.Name}({argument})\n    {{");
            entry.AppendLine($"        if (!TryEnter()) return AbiConvert.Failure{failure}(NativeFailureStatus.HostError, \"concurrent or reentrant host call\");");
            entry.AppendLine("        var failureStatus = NativeFailureStatus.HostError;\n        try\n        {\n            var current = CurrentHost();");
            if (operation.Input is {} request)
                entry.AppendLine($"            failureStatus = NativeFailureStatus.InvalidArgument;\n            var request = AbiConvert.Read{request.Name}(input);");
            entry.AppendLine("            failureStatus = NativeFailureStatus.SemanticError;");
            string call = $"current.{operation.Name}({(operation.Input is null ? "" : "request")})";
            if (operation.Result is {} value) entry.AppendLine($"            return AbiConvert.Write{value.Name}({call});");
            else entry.AppendLine($"            {call};\n            return AbiConvert.WriteAck();");
            entry.AppendLine($"        }}\n        catch (Exception error) {{ return AbiConvert.Failure{failure}(error, failureStatus); }}\n        finally {{ Exit(); }}\n    }}\n");
        }
        entry.AppendLine("}");
        // Build all text before writing, so generation errors cannot truncate output.
        Save(root, AbiOutput, abi.ToString(), check);
        Save(root, EntryOutput, entry.ToString(), check);
    }

    private static void Save(string root, string file, string content, bool check)
    {
        string path = Path.Combine(root, file);
        if (check)
        {
            if (!File.Exists(path) || File.ReadAllText(path) != content)
                throw new InvalidOperationException("Native operation bindings are stale: " + file);
        }
        else
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            if (!File.Exists(path) || File.ReadAllText(path) != content)
                File.WriteAllText(path, content, new UTF8Encoding(false));
        }
    }
}
